// Portfolio Gallery Manifest
const GALLERY_DATA = [
    {
        id: "photo-1",
        src: "images/1.webp",
        fallback: "images/1.jpg",
        thumb: "images/thumbs/1.webp",
        alt: "Bucharest public transport tram in urban movement",
        title: "Urban Tram in Transit",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "28mm",
        aperture: "f/4.5",
        shutter: "1/400s",
        iso: "200",
        location: "Pasajul Basarab, Bucharest",
        tags: ["tram", "transit", "bucharest", "stb", "street", "basarab"]
    },
    {
        id: "photo-2",
        src: "images/2.webp",
        fallback: "images/2.jpg",
        thumb: "images/thumbs/2.webp",
        alt: "Urban street photography scene in Bucharest",
        title: "Bucharest Street Perspective",
        category: "urban",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "35mm",
        aperture: "f/5.0",
        shutter: "1/320s",
        iso: "160",
        location: "Calea Victoriei, Bucharest",
        tags: ["urban", "street", "architecture", "city", "nikon", "calea victoriei"]
    },
    {
        id: "photo-3",
        src: "images/3.webp",
        fallback: "images/3.jpg",
        thumb: "images/thumbs/3.webp",
        alt: "Public transit bus navigating city streets",
        title: "City Bus Route",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "24mm",
        aperture: "f/4.0",
        shutter: "1/500s",
        iso: "200",
        location: "Bulevardul Elisabeta, Bucharest",
        tags: ["bus", "transit", "public transport", "stb", "city", "elisabeta"]
    },
    {
        id: "photo-4",
        src: "images/4.webp",
        fallback: "images/4.jpg",
        thumb: "images/thumbs/4.webp",
        alt: "Modern tram architectural lines and urban transit",
        title: "Transit Lines & Geometry",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "45mm",
        aperture: "f/5.6",
        shutter: "1/640s",
        iso: "250",
        location: "Șoseaua Progresului, Bucharest",
        tags: ["tram", "transit", "geometry", "urban", "architecture", "progresului"]
    },
    {
        id: "photo-5",
        src: "images/5.webp",
        fallback: "images/5.jpg",
        thumb: "images/thumbs/5.webp",
        alt: "City architecture and street perspective",
        title: "Bucharest Urban Lines",
        category: "urban",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "18mm",
        aperture: "f/3.5",
        shutter: "1/250s",
        iso: "100",
        location: "Piața Unirii, Bucharest",
        tags: ["architecture", "urban", "street", "nikon", "perspective", "unirii"]
    },
    {
        id: "photo-6",
        src: "images/6.webp",
        fallback: "images/6.jpg",
        thumb: "images/thumbs/6.webp",
        alt: "Public transport vehicle in Bucharest",
        title: "Urban Commute",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/5.6",
        shutter: "1/320s",
        iso: "400",
        location: "Bulevardul Iancu de Hunedoara, Bucharest",
        tags: ["transit", "commute", "bucharest", "stb", "hunedoara"]
    },
    {
        id: "photo-7",
        src: "images/7.webp",
        fallback: "images/7.jpg",
        thumb: "images/thumbs/7.webp",
        alt: "Urban transportation geometry and reflections",
        title: "City Reflections & Transit",
        category: "urban",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "35mm",
        aperture: "f/8.0",
        shutter: "1/200s",
        iso: "100",
        location: "Splaiul Independenței, Bucharest",
        tags: ["reflections", "urban", "geometry", "nikon", "street", "dambovita"]
    },
    {
        id: "photo-8",
        src: "images/8.webp",
        fallback: "images/8.jpg",
        thumb: "images/thumbs/8.webp",
        alt: "City transit line framed by urban architecture",
        title: "Framed Transit",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "50mm",
        aperture: "f/5.6",
        shutter: "1/400s",
        iso: "200",
        location: "Calea Rahovei, Bucharest",
        tags: ["transit", "framing", "urban", "architecture", "rahovei"]
    },
    {
        id: "photo-9",
        src: "images/9.webp",
        fallback: "images/9.jpg",
        thumb: "images/thumbs/9.webp",
        alt: "Bucharest street life and public transit",
        title: "Bucharest Rhythm",
        category: "urban",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "32mm",
        aperture: "f/4.8",
        shutter: "1/250s",
        iso: "125",
        location: "Bulevardul Magheru, Bucharest",
        tags: ["urban", "city life", "street", "bucharest", "nikon", "magheru"]
    },
    {
        id: "photo-astra",
        src: "images/astra.webp",
        fallback: "images/astra.jpg",
        thumb: "images/thumbs/astra.webp",
        alt: "Astra Imperio tram operating on Bucharest transit lines",
        title: "Astra Imperio Tram",
        category: "transit",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "35mm",
        aperture: "f/5.6",
        shutter: "1/500s",
        iso: "200",
        location: "Linia 41, Bucharest",
        tags: ["astra", "imperio", "tram", "transit", "stb", "green", "modern", "linia 41"]
    },
    {
        id: "photo-andreuptm",
        src: "images/andreuptm.webp",
        fallback: "images/andreuptm.jpg",
        thumb: "images/thumbs/andreuptm.webp",
        alt: "Urban photography detail by andreuptm",
        title: "Urban Perspective Detail",
        category: "urban",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "35mm",
        aperture: "f/2.8",
        shutter: "1/160s",
        iso: "100",
        location: "Bucharest, Romania",
        tags: ["urban", "architecture", "detail", "andreuptm", "nikon"]
    },
    {
        id: "photo-bias-1",
        src: "images/bias-1.webp",
        fallback: "images/bias-1.jpg",
        thumb: "images/thumbs/bias-1.webp",
        alt: "BIAS Bucharest International Airshow aircraft display",
        title: "BIAS Airshow Display",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/800s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "airshow", "aircraft", "aerobatics", "nikon", "baneasa"]
    },
    {
        id: "photo-bias-2",
        src: "images/bias-2.webp",
        fallback: "images/bias-2.jpg",
        thumb: "images/thumbs/bias-2.webp",
        alt: "BIAS airshow fighter jet in flight",
        title: "Fighter Jet Maneuver",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/800s",
        iso: "200",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "jet", "fighter", "flight", "airshow", "nikon"]
    },
    {
        id: "photo-bias-3",
        src: "images/bias-3.webp",
        fallback: "images/bias-3.jpg",
        thumb: "images/thumbs/bias-3.webp",
        alt: "Aviation photography at Bucharest International Airshow",
        title: "Sky High Aerobatics",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/10.0",
        shutter: "1/800s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "aerobatics", "sky", "plane", "nikon"]
    },
    {
        id: "photo-bias-4",
        src: "images/bias-4.webp",
        fallback: "images/bias-4.jpg",
        thumb: "images/thumbs/bias-4.webp",
        alt: "Military aircraft performing flight maneuvers at BIAS",
        title: "Military Flight Dynamics",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/9.0",
        shutter: "1/800s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "military", "aircraft", "maneuver", "nikon"]
    },
    {
        id: "photo-bias-5",
        src: "images/bias-5.webp",
        fallback: "images/bias-5.jpg",
        thumb: "images/thumbs/bias-5.webp",
        alt: "Aerobatic flight display at BIAS Airshow",
        title: "Smoke Trail Formation",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/800s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "smoke", "formation", "aerobatics", "nikon"]
    },
    {
        id: "photo-bias-6",
        src: "images/bias-6.webp",
        fallback: "images/bias-6.jpg",
        thumb: "images/thumbs/bias-6.webp",
        alt: "Airplane flight demonstration at BIAS",
        title: "Flight Demonstration",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/800s",
        iso: "200",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "flight", "plane", "nikon"]
    },
    {
        id: "photo-bias-7",
        src: "images/bias-7.webp",
        fallback: "images/bias-7.jpg",
        thumb: "images/thumbs/bias-7.webp",
        alt: "Aviation exhibition aircraft at Bucharest Airshow",
        title: "Static Airshow Display",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/250s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "exhibition", "aircraft", "nikon"]
    },
    {
        id: "photo-bias-8",
        src: "images/bias-8.webp",
        fallback: "images/bias-8.jpg",
        thumb: "images/thumbs/bias-8.webp",
        alt: "Helicopter flight demonstration at BIAS",
        title: "Helicopter Flight Display",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "40mm",
        aperture: "f/11.0",
        shutter: "1/500s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "helicopter", "rotor", "flight", "nikon"]
    },
    {
        id: "photo-bias-9",
        src: "images/bias-9.webp",
        fallback: "images/bias-9.jpg",
        thumb: "images/thumbs/bias-9.webp",
        alt: "Jet formation flight overhead at BIAS",
        title: "Overhead Jet Formation",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/11.0",
        shutter: "1/800s",
        iso: "400",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "formation", "jet", "speed", "nikon"]
    },
    {
        id: "photo-bias-10",
        src: "images/bias-10.webp",
        fallback: "images/bias-10.jpg",
        thumb: "images/thumbs/bias-10.webp",
        alt: "Aviation detail shot at Bucharest Airshow",
        title: "Aviation Geometry & Detail",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "36mm",
        aperture: "f/11.0",
        shutter: "1/800s",
        iso: "400",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "cockpit", "detail", "nikon"]
    },
    {
        id: "photo-bias-11",
        src: "images/bias-11.webp",
        fallback: "images/bias-11.jpg",
        thumb: "images/thumbs/bias-11.webp",
        alt: "Airshow plane soaring through blue sky",
        title: "Blue Sky Climb",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "36mm",
        aperture: "f/11.0",
        shutter: "1/800s",
        iso: "400",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "climb", "sky", "plane", "nikon"]
    },
    {
        id: "photo-bias-12",
        src: "images/bias-12.webp",
        fallback: "images/bias-12.jpg",
        thumb: "images/thumbs/bias-12.webp",
        alt: "Spectacular aviation maneuver at BIAS Bucharest",
        title: "Acrobatic Apex",
        category: "aviation",
        camera: "Nikon D7000",
        lens: "AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        focal: "55mm",
        aperture: "f/8.0",
        shutter: "1/250s",
        iso: "100",
        location: "Băneasa Airport, Bucharest",
        tags: ["aviation", "bias", "aerobatics", "maneuver", "smoke", "nikon"]
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = GALLERY_DATA;
}
